/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AFC_CONSTANTS_H
#define AFC_CONSTANTS_H

#include "AFC_types.h"

namespace afarcloud {

class AFCConstants {
 public:
  AFCConstants();

};

extern const AFCConstants g_AFC_constants;

} // namespace

#endif
