/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AFC_constants.h"

namespace afarcloud {

const AFCConstants g_AFC_constants;

AFCConstants::AFCConstants() {
}

} // namespace

